name: quantum_classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - matplotlib
  - seaborn
  - scikit-learn=1.5.0
  - pytorch=2.3.1
  - torchvision
  - pip:
      - pennylane==0.36.0
      - kaggle==1.6.6
      - timm==1.0.7
      - einops==0.8.0
